In [2]:
import pandas as pd
import numpy as np

# Replace 'your_file.csv' with the actual path to your CSV file
file_path = 'dataset_clean.csv'

# Read CSV file into a pandas DataFrame
df = pd.read_csv(file_path)

# Convert the DataFrame to a NumPy array
numpy_matrix = df.to_numpy()

# Now 'numpy_matrix' contains your data as a NumPy array
print(numpy_matrix)


[[ 1 -1 -1 -1]
 [ 1 -1  1 -1]
 [ 1 -1 -1 -1]
 ...
 [ 1  1  1 -1]
 [-1  1  1 -1]
 [ 1  1  1 -1]]
